name: "Context workflows"

on: [push]

jobs:
    my-context:
      runs-on: ubuntu-latest
      steps:
          - name: "step 1"
            run: |
              echo "Hi $MY_ACTION"
              echo "My repo $MY_REPO"
            env:
                MY_ACTION: ${{ github.action }}
                MY_REPO: ${{ github.action_repository }}
